### PR TITLE
Dandelion io

### LINKED ISSUE #475: Dandelion interoperability
The conversion functions are now implemented on the dandelion side... just keep `to_dandelion` and `from_dandelion` as aliases. 

https://github.com/zktuong/dandelion/issues/261

### PR DESCRIPTION
**Pull request by amoschoomy**
Closes #475 

-   Updated `scirpy.io` `from_dandelion` and `to_dandelion` functions
-   Test fixture for dandelion is updated to reflect `umi_count` changes in dandelion
-    Specify `sc-dandelion` dependency to be at least 0.35 ( in accordance to dandelion changes)

### CODE REVIEW

**Comment by amoschoomy** [comment]
awaiting dandelion package to be updated to 0.35

**Comment by amoschoomy** [comment]
Dandelion 0.35 also integrated `umi_count` changes as mentioned in https://github.com/scverse/scirpy/pull/487#issuecomment-1912601128 so the `test_io.py` have also been updated as well

**Comment by amoschoomy** [comment]
@grst this PR is ready to be reviewed

**Comment by grst** [comment]
Thanks, LGTM!

**Pull request merged**
