### PR TITLE
Update minimal dandelion version

### LINKED ISSUE #343: Cannot convert output from Scirpy to dandelion
### Description of the bug

I try to convert the AnnData after clonal assignment by Scirpy into dandelion format. The result showed that "field productive has invalid bool T + T". I would like to convert it for updating germline sequence of each BCR sequences using dandelion because I did not find this function in Scirpy. However, if you could suggest the other ways. Feel free to let me know.

### Minimal reproducible example

```python
import scirpy as ir

ABC_irdata_exclude_orphan_dandelion = ir.io.to_dandelion(ABC_irdata_exclude_orphan)
ABC_irdata_exclude_orphan_dandelion
```

### The error message produced by the code above

```pytb
~/.conda/envs/dandelion/lib/python3.8/site-packages/airr/schema.py in validate_row(self, row)
    276                 if spec == 'number':  self.to_float(row[f], validate=True)
    277             except ValidationError as e:
--> 278                 raise ValidationError('field %s has %s' %(f, e))
    279 
    280         return True

ValidationError: field productive has invalid bool T + T
```

### Version information

<details>
<summary>versions</summary>

```

```

</details>

### PR DESCRIPTION
**Pull request by grst**
Fix #343

### CODE REVIEW

**Comment by grst** [comment]
@zktuong, is there any chance the new version of dandelion reorders the cells during import or export? 

The round trip conversion fails now, but my first guess would be that just the order is shuffled.

**Comment by zktuong** [comment]
ah, then yes. it will reorder the cells.

**Comment by grst** [comment]
So this is intended behavior? May I ask why you are doing this? 

In any case no problem, I'll just update the test to ignore the order then.

**Comment by zktuong** [comment]
it is. it's to make it more in line with how scirpy orders the contigs by umi counts for chains 1 and 2, and a way we are dealing with trimming/keeping non-productive contigs for some further analyses

**Comment by grst** [comment]
> it is. it's to make it more in line with how scirpy orders the contigs by umi counts for chains 1 and 2, and a way we are dealing with trimming/keeping non-productive contigs for some further analyses

I'm confused. This sounds like reordering the chains again? I belive scirpy keeps the cells in the same order as the input file.

**Comment by zktuong** [comment]
> I'm confused. This sounds like reordering the chains again? I belive scirpy keeps the cells in the same order as the input file.

oh? I was told by the people in the lab that used scirpy that it orders the chains based on umi counts, before selecting which is IR_*_1 and IR_*_2 and uses the highest umi value... so that's why i did it 😅

or does that only happen during clone definition step?

**Comment by grst** [comment]
wait :grinning: 

it **does** order the **chains**. It does not reorder **cells/barcodes**.

**Comment by zktuong** [comment]
ah ok. i think it should be correct overall - i just sort the entire airr contig table based on productive and duplicate_count, which may shift the cell order, but then scirpy reads/loads it in cell by cell and sorts the chain. 

that sounds ok to me.

**Comment by grst** [comment]
Perfect, then I'll just update the test to ignore the order of cells. 

I hope we can converge on a mutual data structure eventually to get rid of conversion issues once and for all (#327). That will take some time unfortunately...

**Pull request merged**
