### PR TITLE
Fix typos in IR query

### PR DESCRIPTION
**Pull request by Zethson**

### CODE REVIEW

**Review by grst — APPROVED** [review]
Good catch, thanks!

**Comment by Zethson** [comment]
@grst 3.9 Windows has some issues. I restart the job already

**Comment by grst** [comment]
Seems that didn't do it. 

Why is CI always such a pain in the neck :see_no_evil: I'll look into it!

**Comment by Zethson** [comment]
Well, Windows CI annoyed me so much that I just killed it. Windows users should use WSL or, you know, go Linux. But this is not the issue for such a discussion, sorry :)

**Pull request merged**
